name: Run plugin-github-api

on:
  push:
    branches: [ main, feat/* ]

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  RUST_LOG: info

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate list.json
        run: |
          wget https://raw.githubusercontent.com/os-checker/kern-crates.github/refs/heads/os-checker/repos-default.json
          jq "to_entries | map(.key)" repos-default.json > list.json
          tree --gitignore -h

      - name: Install plugin-github-api
        run: cargo install --path .

      - name: Run plugin-github-api
        run: |
          os-checker-plugin-github-api # demo_jsons/list.json
          tree --gitignore -h
