name: Run plugin-github-api

on:
  schedule:
    - cron: '0 0/3 * * *'
  push:
    branches: [ main, feat/* ]

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  RUST_LOG: info
  # database branch
  DATABASE: main
  BOT: 1

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate list.json
        run: |
          wget https://raw.githubusercontent.com/os-checker/kern-crates.github/refs/heads/os-checker/repos-default.json
          jq 'to_entries | map(.key) + ["os-checker/os-checker", "os-checker/os-checker.github.io"]' repos-default.json > list.json
          tree --help
          tree --gitignore -h

      - name: Install plugin-github-api
        run: cargo install --path .

      - name: Run plugin-github-api
        run: |
          os-checker-plugin-github-api # demo_jsons/list.json
          tree --gitignore -h tmp

      - name: Push to database
        env:
          PLUGIN_PATH: plugin/github-api
        run: |
          git config --global user.name "zjp-CN"
          git config --global user.email "jiping_zhou@foxmail.com"
          git config --global committer.name "zjp-CN[bot]"
          git config --global committer.email "zjp-CN[bot]@users.noreply.github.com"

          echo "正在 clone os-checker/database"
          git clone https://x-access-token:${{ env.ACCESS_TOKEN }}@github.com/os-checker/database.git
          echo "成功 clone os-checker/database"

          cd database
          git switch ${{ env.DATABASE }}

          rm -rf ${{ env.PLUGIN_PATH }}
          mkdir -p ${{ env.PLUGIN_PATH }}
          mv ../tmp ${{ env.PLUGIN_PATH }}/workflows
          cp ../demo_jsons/push.sh ${{ env.PLUGIN_PATH }}

          bash ${{ env.PLUGIN_PATH }}/push.sh

