name: Run plugin-github-api

on:
  schedule:
    - cron: '0 0/3 * * *'
  push:
    branches: [ main, feat/* ]

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  RUST_LOG: info
  # database branch
  DATABASE: main
  BOT: 1
  TAG_REPOS_DEFAULT: cache-v8.redb
  OS_CHECKER_CONFIGS: repos-default.json repos-ui.json

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate list.json
        run: |
          wget https://github.com/os-checker/database/releases/download/${{ env.TAG_REPOS_DEFAULT }}/repos-default.json
          wget https://raw.githubusercontent.com/os-checker/os-checker/refs/heads/main/assets/repos-ui.json
          # jq 'to_entries | map(.key) + ["os-checker/os-checker", "os-checker/os-checker.github.io"]' repos-default.json > list.json
          tree --help
          tree --gitignore -h

      - name: Install os-checker
        run: |
          wget https://github.com/os-checker/database/releases/download/precompiled-checkers/os-checker -O ~/.cargo/bin/os-checker
          chmod +x ~/.cargo/bin/os-checker
          os-checker config --list-repos

      - name: Install plugin-github-api
        run: cargo install --path .

      - name: Run plugin-github-api
        run: |
          os-checker-plugin-github-api # demo_jsons/list.json
          tree --gitignore -h github-api

      - name: Push to database
        env:
          PLUGIN_PATH: plugin/github-api
        run: |
          git config --global user.name "zjp-CN[bot]"
          git config --global user.email "zjp-CN[bot]@users.noreply.github.com"
          git config --global committer.name "zjp-CN[bot]"
          git config --global committer.email "zjp-CN[bot]@users.noreply.github.com"

          echo "正在 clone os-checker/database"
          git clone https://x-access-token:${{ env.ACCESS_TOKEN }}@github.com/os-checker/database.git
          echo "成功 clone os-checker/database"

          cd database
          git switch ${{ env.DATABASE }}

          rm -rf ${{ env.PLUGIN_PATH }}
          mkdir -p plugin
          mv ../github-api plugin
          bash ../demo_jsons/push.sh
